- name: Install Curl package
  become: true
  apt:
    name: curl
    state: present

- name: Install NVM (Node Version Manager)
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
  environment:
    HOME: /root
  register: nvm_installation

- name: Source NVM script
  shell: . ~/.nvm/nvm.sh
  args:
    executable: /bin/bash

- name: Install Node.js version 18
  shell: . ~/.nvm/nvm.sh && nvm install 18
  args:
    executable: /bin/bash

- name: Set default Node.js version to 18
  shell: . ~/.nvm/nvm.sh && nvm alias default 18
  args:
    executable: /bin/bash

- name: Install npm and pm2 globally
  shell: |
    apt install npm -y
    npm install pm2 -g

- name: Add Yarn GPG
  become: true
  shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

- name: Add Yarn repository
  become: true
  shell: echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list
  notify: Update apt package cache

- name: Install Yarn
  apt:
    name: yarn
    update_cache: yes
    state: present

- name: Clone the repository
  git:
    repo: 'https://github.com/elshiraphine/fe-todo.git'
    dest: '/var/www/fe-todo'
    clone: yes
    update: yes
    force: yes
  become: true
  become_user: www-data

- name: Set permissions on the repository
  file:
    path: '/var/www/fe-todo'
    state: directory
    mode: '0777'

- name: Remove package-lock.json to avoid conflicts
  file:
    path: "/var/www/fe-todo/package-lock.json"
    state: absent

- name: Run yarn install to install dependencies
  become: true
  shell: |
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm use 18 && yarn install"
  args:
    chdir: "/var/www/fe-todo"
    executable: /bin/bash

- name: Build the project using yarn
  become: true
  shell: |
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm use 18 && yarn build"
  args:
    chdir: "/var/www/fe-todo"
    executable: /bin/bash

- name: Run yarn start to start the project
  become: true
  shell: |
    /bin/bash -c "source ~/.nvm/nvm.sh && yarn start"
  args:
    chdir: "/var/www/fe-todo"
  async: 1000
  poll: 0
  ignore_errors: yes
  register: result

- name: Start PM2
  shell: pm2 start --name fe-todo "yarn start"
  args:
    chdir: "/var/www/fe-todo"
